/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { INFileT, INFileTInterface } from "../INFileT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class INFileT__factory {
  static readonly abi = _abi;
  static createInterface(): INFileTInterface {
    return new utils.Interface(_abi) as INFileTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INFileT {
    return new Contract(address, _abi, signerOrProvider) as INFileT;
  }
}
